// constants.ts
export const USER_MODEL = 'USER_MODEL';
export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const  jwtConstants = {
    secret: 'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
  };